---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: gotk-system
spec:
  interval: 1m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  generation: 2
  name: ingress-nginx-info
  namespace: gotk-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
  - kind: HelmRepository
    name: nginx-ingress
  - kind: HelmChart
    name: nginx-ingress
  - kind: HelmRelease
    name: nginx-ingress
    namespace: networking
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: networking
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  interval: 5m
  releaseName: nginx-ingress
  helmVersion: v3
  rollback:
    enable: false
  chart:
    spec:
      version: 2.13.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: gotk-system
      interval: 1m
  values:
    controller:
      ingressClass: nginx
      replicaCount: 1
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.10.21
      publishService:
        enabled: true
      config:
        #ssl-protocols: "TLSv1.3 TLSv1.2"
        # Setting use-proxy-protocol to true will break the proxy
        use-proxy-protocol: "false"
        proxy-body-size: "0"
        use-forwarded-headers: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: networking
      extraArgs:
        default-ssl-certificate: "networking/acme-crt-secret"
      nodeSelector:
        kubernetes.io/hostname: io
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 500Mi
    defaultBackend:
      enabled: false