---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 1m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: networking
      interval: 1m
  values:
    controller:
      ingressClass: nginx
      replicaCount: 1
      service:
        type: LoadBalancer
        loadBalancerIP: 10.60.0.10
      publishService:
        enabled: true
      config:
        #ssl-protocols: "TLSv1.3 TLSv1.2"
        # Setting use-proxy-protocol to true will break the proxy
        use-proxy-protocol: "false"
        proxy-body-size: "0"
        use-forwarded-headers: "true"
      #metrics:
      #  enabled: true
      #  serviceMonitor:
      #    enabled: true
      #    namespace: networking
      extraArgs:
        default-ssl-certificate: "networking/acme-crt-secret"
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 500Mi
    defaultBackend:
      enabled: false