---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metallb
  namespace: gotk-system
spec:
  interval: 1m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  generation: 2
  name: metallb-info
  namespace: gotk-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
  - kind: HelmRepository
    name: metallb
  - kind: HelmChart
    name: metallb
  - kind: HelmRelease
    name: metallb
    namespace: networking
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: metallb
  helmVersion: v3
  rollback:
    enable: false
  chart:
    spec:
      sourceFrom:
        repository: https://charts.bitnami.com/bitnami
        name: metallb
        namespace: gotk-system
      version: 0.1.24
  values:
    configInLine:
      address-pools:
        addresses:
          - 192.168.10.21-192.168.10.25
    speaker:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64