apiVersion: v1
kind: ConfigMap
metadata:
  namespace: networking
  name: metallb
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.60.0.51-10.60.0.55