---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: iot
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  strategy:
    type: Replace
  releaseName: mosquitto
  helmVersion: v3
  chart:
    repository: https://k8s-at-home.com/charts/
    name: mosquitto
    version: 0.3.3
  values:
    nodeSelector:
      beta.kubernetes.io/hostname: io
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.10.2
    persistence:
      enabled: true
      existingClaim: mosquitto-pvc
    customConfig: |
      listener 1883
      password_file /mosquitto/config/password.conf