---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: iot
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  replica: 1
  releaseName: mosquitto
  helmVersion: v3
  chart:
    repository: https://k8s-at-home.com/charts/
    name: mosquitto
    version: 0.3.3
  values:
    nodeSelector:
      kubernetes.io/hostname: io
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.10.21
    persistence:
      enabled: true
      existingClaim: mosquitto-pvc
    customConfig:
      mosquitto.conf: |
        port 1883
        password_file /mosquitto/config/password.conf
        allow_anonymous false
        persistence true
        persistence_location /mosquitto/data
        persistence_file /mosquitto/data/mosquitto.db
        
      password.conf: |
        mqtt:$6$AEuVLzJVEoVxTCAT$0U7sFehXmvBI9xIbqkEa0jM0ExQidD0QNX/PvwPQZF8GpmXTB5z7l5rRE7/x5Rq/+FpmMpMZTL25i8uu2fOTOg==