---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: iot
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  replica: 1
  releaseName: mosquitto
  helmVersion: v3
  chart:
    repository: https://charts.itstoni.com/
    name: mosquitto
    version: 1.0.1
  values:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.10.22
      externalTrafficPolicy: Local
    persistence:
      enabled: true
      existingClaim: mosquitto-pvc
    auth:
      secretName: mosquitto-auth
      secretKey: mqtt-password
