---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: iot
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  replica: 1
  releaseName: mosquitto
  helmVersion: v3
  chart:
    repository: https://k8s-at-home.com/charts/
    name: mosquitto
    version: 0.3.3
  values:
    nodeSelector:
      kubernetes.io/hostname: io
    service:
      type: ClusterIP
    persistence:
      enabled: true
      existingClaim: mosquitto-pvc
      