---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: iot
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  replica: 1
  releaseName: mosquitto
  helmVersion: v3
  chart:
    repository: https://storage.googleapis.com/t3n-helm-charts
    name: mosquitto
    version: 2.0.0
  values:
    nodeSelector:
      kubernetes.io/hostname: io
    service:
      type: ClusterIP
      annotations:
        metallb.universe.tf/allow-shared-ip: io
    persistence:
      enabled: true
      existingClaim: mosquitto-pvc
    authentication:
      passwordEntries: |
        mqtt:$6$AEuVLzJVEoVxTCAT$0U7sFehXmvBI9xIbqkEa0jM0ExQidD0QNX/PvwPQZF8GpmXTB5z7l5rRE7/x5Rq/+FpmMpMZTL25i8uu2fOTOg==