---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: iot
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  replica: 1
  releaseName: mosquitto
  helmVersion: v3
  chart:
    repository: https://charts.itstoni.com/
    name: mosquitto
  values:
    nodeSelector:
      kubernetes.io/hostname: io
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: io
    persistence:
      enabled: true
      existingClaim: mosquitto-pvc
    passwordEntries: |
      mqtt:$6$UWxhmhWYEY1lQALt$yBcPltbdYN3exQxcZuaBL9hHq99fN0Se4oQcNh4xEhIdPE+Z9bnPn9maoS/WqqshAtn3QliIQddCVvpd9C7ZNQ==