---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pfc
  namespace: iot
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-data
  resources:
    requests:
      storage: 1Mi