---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: emby
  namespace: iot
  annotations:
    replicas-max: "1"
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
spec:
  releaseName: emby
  rollback:
    enable: false
  chart:
    repository: https://charts.itstoni.com/
    name: emby
    version: 1.0.0
  values:
    persistence:
      enabled: true
      existingClaim: emby-pvc
    shares:
      - name: media
        claimName: nfs-media-pvc
        mountPath: /mnt/media