---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: iot
  annotations:
    replicas-max: "1"
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: plex
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: plex
    version: 2.0.4
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.20.3.3437-f1f08d65b
      pullPolicy: IfNotPresent
    # hostNetwork: true
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - "plex.itstoni.com"
      tls:
      - hosts:
        - "plex.itstoni.com"
    advertiseIp: "http://192.168.10.25:32400"
    timezone: "Asia/Makassar"
    serviceTCP:
      type: LoadBalancer
      loadBalancerIP: 192.168.10.25
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: io
    serviceUDP:
      type: LoadBalancer
      loadBalancerIP: 192.168.10.25
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: io
    persistence:
      config:
        storageClass: "nfs-client"
        size: 5Gi
        accessMode: ReadWriteOnce
      transcode:
        enabled: false
        emptyDir:
          medium: "Memory"
      data:
        enabled: false
      extraMounts:
      - name: media
        claimName: nfs-media-pvc
    #logging:
    #  promtail:
    #    enabled: true
    #    loki:
    #      url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
    resources:
      requests:
        cpu: 35m
        memory: 1500Mi
    #  limits:
    #    gpu.intel.com/i915: 1
    #    memory: 35000Mi
    #affinity:
    #  nodeAffinity:
    #    requiredDuringSchedulingIgnoredDuringExecution:
    #      nodeSelectorTerms:
    #      - matchExpressions:
    #        - key: homelab.gpu/type
    #          operator: In
    #          values:
    #          - "intel"