---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: gotk-system
spec:
  interval: 1m
  url: https://charts.jetstack.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.0.3
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: gotk-system
      interval: 1m
  values:
    installCRDs: true
    webhook:
      enabled: true
      tolerations:
      - key: "arm"
        operator: "Exists"
    extraArgs:
    - --dns01-recursive-nameservers=1.1.1.1:53
    - --dns01-recursive-nameservers-only
    tolerations:
    - key: "arm"
      operator: "Exists"
    cainjector:
      replicaCount: 1
      # extraArgs:
      #   - --leader-elect=false
      tolerations:
      - key: "arm"
        operator: "Exists"
    #prometheus:
    #  enabled: true
    #  servicemonitor:
    #    enabled: true
    #    prometheusInstance: monitoring
