---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: etcd
  namespace: networking
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: etcd
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: etcd
    version: 4.10.1
  values:
    image:
      registry: docker.io
      repository: bitnami/etcd
      tag: 3.4.13
    statefulset:
      replicaCount: 1
    auth:
      rbac:
        enabled: false
    persistence:
      enabled: false
      # storageClass: "longhorn"
      # size: 8Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true