---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: networking
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: nginx-ingress
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.13.0
  values:
    controller:
      ingressClass: nginx
      replicaCount: 1
      service:
        type: LoadBalancer
        externalIPs:
        - 192.168.10.21
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: io
      publishService:
        enabled: true
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        # Setting use-proxy-protocol to true will break the proxy
        use-proxy-protocol: "false"
        proxy-body-size: "0"
        use-forwarded-headers: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: networking
      extraArgs:
        default-ssl-certificate: "networking/acme-crt-secret"
      nodeSelector:
        kubernetes.io/hostname: io
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 500Mi
    defaultBackend:
      enabled: false