---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: traefik
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://helm.traefik.io/traefik
    name: traefik
    version: 1.87.2
  values:
    ssl:
      enabled: "true"
      insecureSkipVerify: "true" 
    metrics:
      prometheus:
        enabled: "true"
      serviceMonitor:
        enabled: "true" 
    dashboard:
      enabled: "true"
      serviceType: "LoadBalancer"
      auth:
        basic:
          admin: "$apr1$nm9IfRg3$INl.uQ2TN4BQco/PfdNlq1" 
    loadBalancerIP: 192.168.10.2
    logLevel: "debug"