---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: traefik
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://helm.traefik.io/traefik
    name: traefik
    version: 9.7.0
  values:
    ssl:
      enabled: true
      insecureSkipVerify: true
    metrics:
      prometheus:
        enabled: true
      serviceMonitor:
        enabled: true
    ingressRoute:
      dashboard:
        enabled: true
        #auth:
        #  basic:
        #    admin: "$apr1$nm9IfRg3$INl.uQ2TN4BQco/PfdNlq1"
    service:
      spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.10.2
    logLevel: debug