---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasmota-pvc
  namespace: iot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-sc
  resources:
    requests:
      storage: 1Gi