git:
  url: "git@github.com:kilip/olympus-k3s-gitops.git"
  branch: master
  path: deployments
  user: "onedr0p"
  email: "onedr0p@users.noreply.github.com"
image:
  repository: docker.io/fluxcd/flux
  tag: 1.21.0
memcached:
  enabled: true
syncGarbageCollection:
  enabled: true
  dry: false
prometheus:
  enabled: true
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux