---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: helm-operator
  helmVersion: v3
  chart:
    repository: https://charts.fluxcd.io/
    name: helm-operator
    version: 1.2.0
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/kilip/olympus-k3s-gitops/master/deployments/flux/helm-operator-values.yaml