---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-pvc
  namespace: iot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
