---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-pv
  namespace: iot
spec:
  storageClassName: nfs-data
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.100.2
    path: /mnt/hd1/data
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576