kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-sc
  namespace: iot
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: "longhorn-sc"