- hosts: all
  become: true
  tasks:
    - name: "run preflight tasks"
      include_role:
        name: preflight
  
- name: "include k3s-clusters tasks"
  import_playbook: "{{ playbook_dir }}/vendor/k3s-ansible/site.yml"