---
k3s_version: v1.18.8+k3s1
ansible_user: toni
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"


extra_server_args: |
  --disable servicelb \
  --disable traefik \
  --disable metrics-server \
  --disable local-storage \
  --flannel-backend host-gw \
  --kubelet-arg "feature-gates=ExternalPolicyForExternalIP=true"

extra_agent_args: |
  --kubelet-arg="feature-gates=ExternalPolicyForExternalIP=true"
