apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: longhorn
  helmVersion: v3
  chart:
    repository: https://charts.longhorn.io
    name: longhorn
    version: 1.0.2
  values:
    persistence:
      defaultClassReplicaCount: 1
    defaultSettings:
      defaultReplicaCount: 1
      createDefaultDiskLabeledNodes: true
      backupTarget: nfs://192.168.100.2:/mnt/hd1/k8s
      defaultDataPath: /srv/longhorn
    csi:
      resizerReplicaCount: 1
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      host: "longhorn.itstoni.com"
    taintToleration:
      - key: beta.kubernetes.io/arch
        operator: Equal
        value: arm64
        effect: NoSchedule