apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~v3.1
spec:
  releaseName: nfs-client-provisioner
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nfs-client-provisioner
    version: 1.2.9
  values:
    nodeSelector:
      kubernetes.io/arch: amd64
    image:
      repository: quay.io/external_storage/nfs-client-provisioner
      tag: v3.1.0-k8s1.11
    nfs:
      server: "192.168.100.2"
      path: "/mnt/hd1/k8s/nfs"
    storageClass:
      defaultClass: false