---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rancher
  namespace: system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: rancher
  helmVersion: v3
  chart:
    repository: https://releases.rancher.com/server-charts/stable
    name: rancher
    version: 2.4.8
  values:
    hostname: "rancher.itstoni.com"
    ingress:
      tls:
        source: secret
    proxy: http://192.168.100.11:3128
    noProxy: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    replicas: 3